const data = [
  {
    data: [
      { name: '河南', value: '92.87' },
      { name: '江苏', value: '90.75' },
      { name: '天津', value: '99.04' },
      { name: '山东', value: '95.71' },
      { name: '黑龙江', value: '86.68' },
      { name: '北京', value: '96.75' },
      { name: '安徽', value: '94.99' },
      { name: '上海', value: '98.64' },
      { name: '山西', value: '91.67' },
      { name: '海南', value: '69.66' },
      { name: '陕西', value: '87.90' },
      { name: '广东', value: '74.61' },
      { name: '内蒙古', value: '85.71' },
      { name: '浙江', value: '77.35' },
      { name: '河北', value: '89.33' },
      { name: '重庆', value: '71.25' },
      { name: '辽宁', value: '74.35' },
      { name: '吉林', value: '81.57' },
      { name: '宁夏', value: '82.71' },
      { name: '江西', value: '88.58' },
      { name: '新疆', value: '79.99' },
      { name: '福建', value: '58.99' },
      { name: '贵州', value: '62.59' },
      { name: '湖南', value: '64.31' },
      { name: '广西', value: '51.89' },
      { name: '甘肃', value: '54.42' },
      { name: '湖北', value: '44.61' },
      { name: '云南', value: '9.56' },
      { name: '四川', value: '12.80' },
      { name: '青海', value: '17.16' },
      { name: '西藏', value: '3.62' },
    ],
    rank: [
      ['天津', 99],
      ['上海', 98],
      ['北京', 97],
      ['山东', 96],
      ['安徽', 95],
      ['河南', 93],
      ['山西', 91],
      ['江苏', 90],
      ['河北', 89],
      ['江西', 88],
    ],
    year: 2018,
    year_percent: 73.32,
  },
  {
    data: [
      { name: '河南', value: 87 },
      { name: '江苏', value: 85 },
      { name: '天津', value: 95 },
      { name: '山东', value: 87 },
      { name: '黑龙江', value: 81 },
      { name: '北京', value: 90 },
      { name: '安徽', value: 91 },
      { name: '上海', value: 95 },
      { name: '山西', value: 87 },
      { name: '海南', value: 60 },
      { name: '陕西', value: 84 },
      { name: '广东', value: 66 },
      { name: '内蒙古', value: 82 },
      { name: '浙江', value: 70 },
      { name: '河北', value: 83 },
      { name: '重庆', value: 68 },
      { name: '辽宁', value: 71 },
      { name: '吉林', value: 76 },
      { name: '宁夏', value: 80 },
      { name: '江西', value: 79 },
      { name: '新疆', value: 76 },
      { name: '福建', value: 54 },
      { name: '贵州', value: 60 },
      { name: '湖南', value: 57 },
      { name: '广西', value: 54 },
      { name: '甘肃', value: 58 },
      { name: '湖北', value: 49 },
      { name: '云南', value: 8 },
      { name: '四川', value: 12 },
      { name: '青海', value: 12 },
      { name: '西藏', value: 4 },
    ],
    rank: [
      ['天津', 95],
      ['上海', 95],
      ['安徽', 91],
      ['北京', 90],
      ['河南', 87],
      ['山东', 87],
      ['山西', 87],
      ['江苏', 85],
      ['陕西', 84],
      ['河北', 83],
    ],
    year: 2019,
    year_percent: 68.84,
  },
  {
    data: [
      { name: '贵州', value: 61 },
      { name: '河南', value: 90 },
      { name: '山东', value: 91 },
      { name: '四川', value: 13 },
      { name: '江苏', value: 86 },
      { name: '青海', value: 12 },
      { name: '福建', value: 61 },
      { name: '浙江', value: 72 },
      { name: '湖北', value: 41 },
      { name: '天津', value: 97 },
      { name: '江西', value: 87 },
      { name: '西藏', value: 5 },
      { name: '黑龙江', value: 85 },
      { name: '重庆', value: 69 },
      { name: '云南', value: 11 },
      { name: '北京', value: 97 },
      { name: '广西', value: 56 },
      { name: '陕西', value: 88 },
      { name: '新疆', value: 80 },
      { name: '甘肃', value: 54 },
      { name: '河北', value: 86 },
      { name: '吉林', value: 79 },
      { name: '广东', value: 71 },
      { name: '湖南', value: 56 },
      { name: '宁夏', value: 83 },
      { name: '安徽', value: 94 },
      { name: '内蒙古', value: 84 },
      { name: '上海', value: 98 },
      { name: '山西', value: 89 },
      { name: '海南', value: 65 },
      { name: '辽宁', value: 73 },
    ],
    rank: [
      ['上海', 98],
      ['天津', 97],
      ['北京', 97],
      ['安徽', 94],
      ['山东', 91],
      ['河南', 90],
      ['山西', 89],
      ['陕西', 88],
      ['江西', 87],
      ['江苏', 86],
      ['河北', 86],
      ['黑龙江', 85],
      ['内蒙古', 84],
      ['宁夏', 83],
      ['新疆', 80],
      ['吉林', 79],
      ['辽宁', 73],
      ['浙江', 72],
      ['广东', 71],
      ['重庆', 69],
      ['海南', 65],
      ['福建', 61],
      ['贵州', 61],
      ['湖南', 56],
      ['广西', 56],
      ['甘肃', 54],
      ['湖北', 41],
      ['四川', 13],
      ['青海', 12],
      ['云南', 11],
      ['西藏', 5],
    ],
    year: 2020,
    year_percent: 71.19,
  },
  {
    data: [
      { name: '山东', value: 89 },
      { name: '江苏', value: 83 },
      { name: '广东', value: 75 },
      { name: '内蒙古', value: 81 },
      { name: '山西', value: 85 },
      { name: '河南', value: 87 },
      { name: '新疆', value: 80 },
      { name: '浙江', value: 75 },
      { name: '安徽', value: 92 },
      { name: '河北', value: 81 },
      { name: '贵州', value: 64 },
      { name: '四川', value: 15 },
      { name: '青海', value: 16 },
      { name: '福建', value: 60 },
      { name: '湖北', value: 46 },
      { name: '天津', value: 97 },
      { name: '江西', value: 86 },
      { name: '西藏', value: 4 },
      { name: '黑龙江', value: 82 },
      { name: '重庆', value: 72 },
      { name: '云南', value: 13 },
      { name: '北京', value: 96 },
      { name: '广西', value: 59 },
      { name: '陕西', value: 87 },
      { name: '甘肃', value: 58 },
      { name: '吉林', value: 76 },
      { name: '湖南', value: 61 },
      { name: '宁夏', value: 79 },
      { name: '上海', value: 98 },
      { name: '海南', value: 67 },
      { name: '辽宁', value: 69 },
    ],
    rank: [
      ['上海', 98],
      ['天津', 97],
      ['北京', 96],
      ['安徽', 92],
      ['山东', 89],
      ['陕西', 87],
      ['河南', 87],
      ['江西', 86],
      ['山西', 85],
      ['江苏', 83],
      ['黑龙江', 82],
      ['内蒙古', 81],
      ['河北', 81],
      ['新疆', 80],
      ['宁夏', 79],
      ['吉林', 76],
      ['广东', 75],
      ['浙江', 75],
      ['重庆', 72],
      ['辽宁', 69],
      ['海南', 67],
      ['贵州', 64],
      ['湖南', 61],
      ['福建', 60],
      ['广西', 59],
      ['甘肃', 58],
      ['湖北', 46],
      ['青海', 16],
      ['四川', 15],
      ['云南', 13],
      ['西藏', 4],
    ],
    year: 2021,
    year_percent: 71.13,
  },
  {
    data: [
      { name: '山东', value: 88 },
      { name: '江苏', value: 81 },
      { name: '广东', value: 75 },
      { name: '内蒙古', value: 81 },
      { name: '山西', value: 86 },
      { name: '河南', value: 85 },
      { name: '新疆', value: 80 },
      { name: '浙江', value: 75 },
      { name: '安徽', value: 92 },
      { name: '河北', value: 81 },
      { name: '贵州', value: 64 },
      { name: '四川', value: 15 },
      { name: '青海', value: 16 },
      { name: '福建', value: 60 },
      { name: '湖北', value: 46 },
      { name: '天津', value: 96 },
      { name: '江西', value: 84 },
      { name: '西藏', value: 4 },
      { name: '黑龙江', value: 82 },
      { name: '重庆', value: 72 },
      { name: '云南', value: 13 },
      { name: '北京', value: 97 },
      { name: '广西', value: 59 },
      { name: '陕西', value: 87 },
      { name: '甘肃', value: 58 },
      { name: '吉林', value: 76 },
      { name: '湖南', value: 61 },
      { name: '宁夏', value: 79 },
      { name: '上海', value: 97 },
      { name: '海南', value: 67 },
      { name: '辽宁', value: 69 },
    ],
    rank: [
      ['北京', 97],
      ['上海', 97],
      ['天津', 96],
      ['安徽', 92],
      ['山东', 88],
      ['陕西', 87],
      ['山西', 86],
      ['河南', 85],
      ['江西', 84],
      ['江苏', 81],
      ['黑龙江', 81],
      ['内蒙古', 81],
      ['河北', 81],
      ['新疆', 80],
      ['宁夏', 79],
      ['吉林', 76],
      ['广东', 75],
      ['浙江', 75],
      ['重庆', 72],
      ['辽宁', 69],
      ['海南', 67],
      ['贵州', 64],
      ['湖南', 61],
      ['福建', 60],
      ['广西', 59],
      ['甘肃', 58],
      ['湖北', 46],
      ['青海', 16],
      ['四川', 15],
      ['云南', 13],
      ['西藏', 4],
    ],
    year: 2022,
    year_percent: 66.5,
  },
];

export const resData = {
  max: 100,
  data,
};
